[package]
name = "modular-arithmetic-visualizer"
version = "0.1.0"
authors = ["Jason Gonzales"]
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
nannou = "0.19"
nannou_egui = "0.19.0"
